export const team = {
	management: [
		{
			name: 'Anton Dziatkovskii',
			photo: '/images/members/management-team/anton-rounded.webp',
			position: 'Co-founder',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/anton-dzyatkovskiy/',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Anna Dzyatkovskaya',
			photo: '/images/members/finance-team/anna.webp',
			position: 'CFO',
			socials: [],
		},
		{
			name: 'Olesya Zagorodnikova',
			photo: '/images/members/finance-team/olesya.webp',
			position: 'Finance analysis manager',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/olesya-zagorodnikova-062b33194/',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Helena Kondricheva',
			photo: '/images/members/finance-team/helena.webp',
			position: 'Finance assistant',
			socials: [],
		},
		{
			name: 'Veronika Yurina',
			photo: '/images/members/marketing-pr-team/veronika-yurina.webp',
			position: 'Copywriter',
			socials: [],
		},
		{
			name: 'Anton Flotsky',
			photo: '/images/members/marketing-pr-team/antonFlt.webp',
			position: 'E-mail marketing specialist',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/anton-flotskiy-a21079160/',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Anton Safronov',
			photo: '/images/members/marketing-pr-team/antonSafronov.webp',
			position: 'Live Stream Production Manager',
			socials: [],
		},
		{
			name: 'Viktoria Hrab',
			photo: '/images/members/marketing-pr-team/VictoriaHrab.webp',
			position: 'Assistant',
			socials: [],
		},
		{
			name: 'Vladimir Grinevsky',
			photo: '/images/members/marketing-pr-team/grinevskiy.webp',
			position: 'Head of Editorial office',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/vlad-grin/',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Denis Sinyavsky',
			photo: '/images/members/marketing-pr-team/denis.webp',
			position: 'Copywriter   ',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/denis-sinyavskiy/',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Jitendra Rathod',
			photo: '/images/members/marketing-pr-team/jitendra.webp',
			position: 'Copywriter   ',
			socials: [],
		},
		{
			name: 'Demetra Poyiadzis',
			photo: '/images/members/marketing-pr-team/DemetraPoyiadzis.webp',
			position: 'Proofreader',
			socials: [],
		},
		{
			name: 'Anastasia Kim',
			photo: '/images/members/marketing-pr-team/kim.webp',
			position: 'SMM assistant',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/rimma-khanaeva-35b736b0/',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Irina Shakhin',
			photo: '/images/members/community-management-team/Shakhin.webp',
			position: 'Assistant',
			socials: [],
		},
		{
			name: 'Ekaterina Kurtova ',
			photo: '/images/members/prototypes-bureau/EkaterinaKurtova.webp',
			position: 'Motion Designer',
			socials: [],
		},
		{
			name: 'Inna Kidishuk',
			photo: '/images/members/legal-team/inna.webp',
			position: 'Legal assistant',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/inna-k-168922170 ',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Anna Pislegina',
			photo: '/images/members/legal-team/pislegina.webp',
			position: 'Legal assistant',
			socials: [
				{
					name: 'linkedin',
					link: 'http://www.linkedin.com/in/AnnPislegina',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Ivan Bukatov',
			photo: '/images/members/community-growth-team/ivan.webp',
			position: 'Bounty  Manager',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/ivan-bukatov-0b3baa155/',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Vladislav Korenyugin',
			photo: '/images/members/community-growth-team/vladislav.webp',
			position: 'Researcher',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/korenyugin',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Artem Finko',
			photo: '/images/members/community-growth-team/finko.webp',
			position: 'Bounty  Manager',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/artem-finko-425046156/',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Aleksandra Krylova',
			photo: '/images/members/hr-team/krylova-rounded.webp',
			position: 'Head of HR team',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/alexkrylova/',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Nataliya Lebedeva',
			photo: '/images/members/hr-team/lebedeva.webp',
			position: 'HR Manager',
			socials: [
				{
					name: 'linkedin',
					link: 'https://www.linkedin.com/in/NatalyaLe/',
					icon: '/images/socials/linkedin.svg',
				},
			],
		},
		{
			name: 'Stanislav Kariukin',
			photo: '/images/members/trading-team/stanislav.webp',
			position: 'Head of CryptoFund and Traders',
			socials: [],
		},
		{
			name: 'Evgenii Komlichenko',
			photo: '/images/members/trading-team/evgenii.webp',
			position: 'Assistant trader',
			socials: [],
		},
		{
			name: 'Sergii Dorokhov',
			photo: '/images/members/trading-team/sergii.webp',
			position: 'Trader',
			socials: [],
		},
		{
			name: 'Layli Burieva',
			photo: '/images/members/trading-team/layli.webp',
			position: 'Financial operations support',
			socials: [],
		},
		{
			name: 'Natalia Semerikova',
			photo: '/images/members/trading-team/natalia.webp',
			position: 'Project Manager',
			socials: [],
		},
		{
			name: 'Talgat Musin',
			photo: '/images/members/community-management-team/talgat-musin.webp',
			position: 'Community manager',
			socials: [],
		},
		{
			name: 'Natalia Averianova',
			photo: '/images/members/community-management-team/natalia-averianova.webp',
			position: 'Project Manager',
			socials: [],
		},
		{
			name: 'Kristina Ivanova',
			photo: '/images/members/community-management-team/kristina-ivanova.webp',
			position: 'Education Specialist/ Project Manager',
			socials: [],
		},
		{
			name: 'Veronika Voitko',
			photo: '/images/members/community-management-team/VeronikaVoitko.webp',
			position: 'Copywriter',
			socials: [],
		},
		{
			name: 'Nadezhda Bulkina',
			photo: '/images/members/community-management-team/NadezhdaBulkina.webp',
			position: 'Copywriter',
			socials: [],
		},
		{
			name: 'Ivan Shumkov',
			photo: '/images/members/community-management-team/IvanShumkov.webp',
			position: 'Assistant',
			socials: [],
		},
		{
			name: 'Vladislav Pavlenko',
			photo: '/images/members/community-management-team/VladislavPavlenko.webp',
			position: 'Account manager',
			socials: [],
		},
		{
			name: 'Alexander Dudov',
			photo: '/images/members/community-management-team/alexander-dudov.webp',
			position: 'Researcher/Junior Project',
			socials: [],
		},
		{
			name: 'Alexander Gnilomedov',
			photo: '/images/members/community-management-team/alexander-gnilomedov.webp',
			position: 'Community manager',
			socials: [],
		},
		{
			name: 'Alina Samoylova',
			photo: '/images/members/community-management-team/Samoylova.webp',
			position: 'Community manager',
			socials: [],
		},
		{
			name: 'Marina Pertseva',
			photo: '/images/members/community-management-team/Pertseva.webp',
			position: 'Community manager',
			socials: [],
		},
		{
			name: 'Anastasia Bobkova',
			photo: '/images/members/community-management-team/Bobkova.webp',
			position: 'HR manager',
			socials: [],
		},
		{
			name: 'Yulia Pack',
			photo: '/images/members/yuliaPack.webp',
			position: 'Translator',
			socials: [],
		},
	],
	champions: [
		{
			name: 'Sergey',
			photo: '/images/members/trading-team/sergey.webp',
			position: 'Full Stack developer',
			socials: [],
		},
		{
			name: 'Denis',
			secondName: 'Udot',
			photo: '/images/members/it-champions-team/udot.webp',
			position: 'Technical Project Manager',
			socials: [],
		},
		{
			name: 'Alexey',
			secondName: 'Adylshin',
			photo: '/images/members/it-champions-team/alexey.webp',
			position: 'Lead Architect',
			socials: [],
		},
		{
			name: 'Federiko',
			secondName: 'Kozhemyakin',
			photo: '/images/members/it-champions-team/fedor.webp',
			position: 'Full Stack developer',
			socials: [],
		},
		{
			name: 'Artem',
			secondName: 'Starchkov',
			photo: '/images/members/it-champions-team/starchkov.webp',
			position: 'Full Stack developer',
			socials: [],
		},
		{
			name: 'Ekaterina',
			secondName: 'Ezerskaya',
			photo: '/images/members/btcnext-team/katerina.webp',
			position: 'Frontend developer',
			socials: [],
		},
		{
			name: 'Anton',
			secondName: 'Molchanov',
			photo: '/images/members/btcnext-team/anton.webp',
			position: 'Lead QA',
			socials: [],
		},
		{
			name: 'Daria',
			secondName: '',
			photo: '/images/members/btcnext-team/daria.webp',
			position: 'Full Stack developer',
			socials: [],
		},
		{
			name: 'Mariya',
			secondName: 'Danilova',
			photo: '/images/members/btcnext-team/mariya.webp',
			position: 'Project manager',
			socials: [],
		},
		{
			name: 'Nikita',
			secondName: 'Pisarsky',
			photo: '/images/members/btcnext-team/nikita.webp',
			position: 'Fullstack developer',
			socials: [],
		},
		{
			name: 'Garik',
			secondName: 'Mikaelian',
			photo: '/images/members/btcnext-team/garik.webp',
			position: 'Frontend developer',
			socials: [],
		},
		{
			name: 'Gleb',
			secondName: 'Taygunov',
			photo: '/images/members/btcnext-team/gleb.webp',
			position: 'Full Stack developer',
			socials: [],
		},
		{
			name: 'Oleg',
			secondName: 'Klyuchkin',
			photo: '/images/members/devops-team/oleg.webp',
			position: 'DevOps engineer',
			socials: [],
		},
		{
			name: 'Michail',
			secondName: 'Lobanov',
			photo: '/images/members/noah-blockchain-team/michail.webp',
			position: 'Frontend developer',
			socials: [],
		},
		{
			name: 'Dmitry',
			secondName: 'Ermilov',
			photo: '/images/members/it-champions-team/Dmitry_Ermilov.webp',
			position: 'Frontend developer',
			socials: [],
		},
		{
			name: 'Khayrullodzhon',
			secondName: 'Rustamov',
			photo: '/images/members/it-champions-team/khayrullodzhon-rustamov.webp',
			position: 'Backend developer',
			socials: [],
		},
		{
			name: 'Roman',
			secondName: '',
			photo: '/images/members/it-champions-team/roman-584.webp',
			position: 'Frontend developer',
			socials: [],
		},
		{
			name: 'Vasiliy',
			secondName: '',
			photo: '/images/members/it-champions-team/vasiliy-530.webp',
			position: 'Database Administrator',
			socials: [],
		},
		{
			name: 'Alexander',
			secondName: '',
			photo: '/images/members/it-champions-team/alexander.webp',
			position: 'Frontend developer',
			socials: [],
		},
		{
			name: 'Danil Garbazhiy',
			photo: '/images/members/community-management-team/Garbazhiy.webp',
			position: 'Frontend developer',
			socials: [],
		},
		{
			name: 'Gurami Niazashvili',
			photo: '/images/members/community-management-team/Niazashvili.webp',
			position: 'Frontend developer',
			socials: [],
		},
		{
			name: 'Rasul',
			photo: '/images/members/it-champions-team/rasul.webp',
			position: 'Frontend developer',
			socials: [],
		},
	],
}
